# Week 6 Lectorial Exercises

Generate and print 5 integers between 0 and 10 from a numpy random number generator after setting its seed.

In [17]:
# Code block 1
import numpy as np

rseed = 1729
rng = np.random.default_rng(seed = rseed)
# Your code here
rng.integers(low=0, high=10, size=5)

array([7, 0, 3, 1, 7], dtype=int64)

Now generate 5 more integers and print them. Now create a random number generator with the same seed as above and generate 5 integers and print them. What do you notice?


In [21]:
# Code block 2
print(rng.integers(low=0, high=10, size=5))
rseed = 1729
rng = np.random.default_rng(seed = rseed)
# Your code here
rng.integers(low=0, high=10, size=5)

[2 0 5 5 8]


array([7, 0, 3, 1, 7], dtype=int64)

Your answer here.

Now let us consider the **period** of a random number generator. This is the number of integers it generates until it repeats in a cycle.

Run the following code fragment and write down what you notice. Look at the code in `not_so_random` and explain why you have got your result. Note that the modulus in this random number generator is 13 so we would hope to have a period of 12 (0 is disallowed as usual).

In [38]:
import not_so_random 

nsr = not_so_random.NotSoRandom()
nsr.seed(10) 
print([nsr.random() for _ in  range(26)])

[4, 12, 10, 4, 12, 10, 4, 12, 10, 4, 12, 10, 4, 12, 10, 4, 12, 10, 4, 12, 10, 4, 12, 10, 4, 12]


Your answer here.

Now try running the code with other seeds. What do you notice?

Your answer here.

Now let us look at generating correlated data from a Gaussian distribution with two variables. This is quite easy using numpy's function `random.multivariate_normal`. (I have used a correlation matrix for the sake of simplicity, but it is not much harder to create a covariance matrix for full generality).

In [39]:
corr = np.array([[1., -0.40],
...                  [-0.40, 1.]])

mean = np.array([2., 0.5])

#Your code here: don't forget to set the seed first
rng = np.random.default_rng(rseed)
data = np.random.multivariate_normal(mean=mean, cov=corr, size=500)

Now we can check on the result: compute the mean and correlation of the data and explain what you see.

In [54]:
# Your code here
print(data.mean(axis=0))
print(np.corrcoef(data,rowvar=False))


[1.9964535  0.51490005]
[[ 1.         -0.47295158]
 [-0.47295158  1.        ]]


Your answer here.